import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.education": "Formation",
    "nav.skills": "Compétences",
    "nav.experience": "Expérience",
    "nav.projects": "Projets",
    "nav.certifications": "Certifications",
    "nav.contact": "Contact",
    
    // Hero
    "hero.greeting": "Bonjour, je suis",
    "hero.title": "Ingénieur Data & IA",
    "hero.description": "Étudiant en Master Ingénierie des Données et Intelligence Artificielle, passionné par le développement de solutions innovantes basées sur l'IA et l'analyse de données.",
    "hero.cta": "Me Contacter",
    "hero.projects": "Voir mes projets",
    "hero.downloadCV": "Télécharger CV",
    
    // About
    "about.title": "À Propos de Moi",
    "about.intro": "Passionné par l'intelligence artificielle et l'ingénierie des données",
    "about.p1": "Je suis actuellement étudiant en Master Ingénierie des Données et Intelligence Artificielle, avec une solide formation en génie logiciel obtenue lors de ma licence.",
    "about.p2": "Mon parcours m'a permis de développer une expertise technique approfondie en Machine Learning, Deep Learning, et en développement d'applications web modernes. Je suis particulièrement intéressé par les solutions qui combinent IA et Big Data pour résoudre des problèmes concrets.",
    "about.p3": "Toujours à la recherche de nouveaux défis, je m'efforce de rester à jour avec les dernières technologies et méthodologies du domaine.",
    "about.highlight1.title": "Intelligence Artificielle",
    "about.highlight1.description": "Spécialisation en Machine Learning et Deep Learning",
    "about.highlight2.title": "Ingénierie des Données",
    "about.highlight2.description": "Expertise en Big Data et pipelines de données",
    "about.highlight3.title": "Génie Logiciel",
    "about.highlight3.description": "Solide formation en développement logiciel",
    
    // Education
    "education.title": "Formation Académique",
    
    // Skills
    "skills.title": "Compétences Techniques",
    "skills.ai": "Intelligence Artificielle",
    "skills.data": "Data Engineering",
    "skills.web": "Développement Web",
    "skills.database": "Bases de Données",
    "skills.tools": "Outils & DevOps",
    "skills.soft": "Soft Skills",
    
    // Experience
    "experience.title": "Expérience Professionnelle",
    
    // Projects
    "projects.title": "Projets",
    "projects.subtitle": "Découvrez mes réalisations en Intelligence Artificielle et développement",
    "projects.filterAll": "Tous",
    "projects.filterAI": "Intelligence Artificielle",
    "projects.filterWeb": "Développement Web",
    "projects.filterData": "Data Science",
    "projects.details": "Détails",
    "projects.github": "GitHub",
    "projects.demo": "Démo",
    "project1.title": "Système de Recommandation Intelligent",
    "project1.description": "Développement d'un système de recommandation basé sur le Machine Learning pour améliorer l'expérience utilisateur",
    "project1.detailedDescription": "Ce projet implémente un système de recommandation utilisant des algorithmes de filtrage collaboratif et de deep learning. Il analyse les comportements utilisateurs pour suggérer du contenu personnalisé avec une précision de 87%.",
    "project2.title": "Pipeline ETL Big Data",
    "project2.description": "Conception d'un pipeline de traitement de données massives pour l'analyse en temps réel",
    "project2.detailedDescription": "Pipeline distribué capable de traiter plusieurs millions d'événements par seconde. Utilise Apache Spark pour le traitement parallèle et Hadoop pour le stockage distribué. Inclut des mécanismes de monitoring et d'alerte en temps réel.",
    "project3.title": "Chatbot IA Conversationnel",
    "project3.description": "Création d'un assistant virtuel utilisant le traitement du langage naturel",
    "project3.detailedDescription": "Assistant conversationnel intelligent basé sur des transformers et capable de comprendre le contexte des conversations. Supporte plusieurs langues et s'intègre facilement via API REST.",
    "project4.title": "Data Warehouse Analytics",
    "project4.description": "Mise en place d'un entrepôt de données pour l'analyse décisionnelle",
    "project4.detailedDescription": "Architecture data warehouse complète avec modélisation en étoile, processus ETL automatisés et dashboards interactifs. Optimisé pour des requêtes analytiques complexes.",
    "project5.title": "Application Web Full-Stack",
    "project5.description": "Développement d'une plateforme web complète avec authentification et gestion de données",
    "project5.detailedDescription": "Application MERN stack moderne avec authentification JWT, gestion d'état Redux, et interface utilisateur responsive. Inclut des tests unitaires et d'intégration complets.",
    "project6.title": "Système de Détection de Fraudes",
    "project6.description": "Modèle ML pour la détection automatique de transactions frauduleuses",
    "project6.detailedDescription": "Système de détection en temps réel utilisant des algorithmes d'anomaly detection. Atteint 95% de précision avec un taux de faux positifs inférieur à 2%.",
    "project7.title": "Plateforme de Sentiment Analysis",
    "project7.description": "Analyse automatique des sentiments dans les avis clients sur les réseaux sociaux",
    "project7.detailedDescription": "Plateforme d'analyse de sentiment multi-langues utilisant des modèles BERT fine-tunés. Traite des milliers de posts par minute avec classification en 5 catégories émotionnelles.",
    "project8.title": "E-commerce avec IA",
    "project8.description": "Site e-commerce intégrant des recommandations personnalisées par IA",
    "project8.detailedDescription": "Plateforme e-commerce complète avec système de recommandation hybride, panier intelligent et prédiction de churn. Augmentation de 40% du taux de conversion.",
    "project9.title": "Computer Vision - Reconnaissance d'objets",
    "project9.description": "Application de détection et classification d'objets en temps réel",
    "project9.detailedDescription": "Application de computer vision utilisant YOLO et des CNNs personnalisés. Capable de détecter 80+ classes d'objets en temps réel avec 30+ FPS.",
    "project10.title": "Dashboard Analytics en Temps Réel",
    "project10.description": "Tableau de bord interactif pour la visualisation de données en streaming",
    "project10.detailedDescription": "Dashboard temps réel construit avec React et D3.js, connecté à Kafka pour le streaming. Inclut des graphiques interactifs, alertes automatiques et exports personnalisables.",
    "project11.title": "Système de Résumé Automatique",
    "project11.description": "Outil d'extraction et de résumé automatique de documents volumineux",
    "project11.detailedDescription": "Outil de summarization extractive et abstractive utilisant BERT et GPT. Capable de résumer des documents de 100+ pages en quelques secondes tout en préservant les informations clés.",
    "project12.title": "API de Prédiction MLaaS",
    "project12.description": "Service cloud pour déployer et consommer des modèles ML via API REST",
    "project12.detailedDescription": "Plateforme MLaaS permettant le déploiement rapide de modèles ML. Auto-scaling, monitoring intégré, et documentation API automatique. Déployé sur AWS avec FastAPI.",
    
    // Certifications
    "certifications.title": "Certifications",
    "certifications.subtitle": "Découvrez mes certificats et distinctions dans le domaine de l'intelligence artificielle et du développement web.",
    "cert1.title": "Certification en Intelligence Artificielle",
    "cert1.institution": "FORCE-N",
    "cert1.date": "Mars 2025",
    "cert1.description": "Attestation de réussite au programme FORCE-N reconnu par l'Union Africaine et Mastercard Foundation",
    "cert2.title": "Certification Web Development",
    "cert2.institution": "Votre Institution",
    "cert2.date": "2024",
    "cert2.description": "Certification en développement web full-stack",
    "cert3.title": "Certification Machine Learning",
    "cert3.institution": "Votre Institution",
    "cert3.date": "2024",
    "cert3.description": "Certification avancée en machine learning et deep learning",
    "cert4.title": "AWS Certified Solutions Architect",
    "cert4.institution": "Amazon Web Services",
    "cert4.date": "2024",
    "cert4.description": "Certification en architecture cloud AWS",
    "cert5.title": "Data Engineering Professional",
    "cert5.institution": "Google Cloud",
    "cert5.date": "2024",
    "cert5.description": "Certification en ingénierie des données sur GCP",
    "cert6.title": "Python for Data Science",
    "cert6.institution": "IBM",
    "cert6.date": "2023",
    "cert6.description": "Certification en programmation Python pour la science des données",
    "cert7.title": "TensorFlow Developer Certificate",
    "cert7.institution": "Google",
    "cert7.date": "2023",
    "cert7.description": "Certification officielle TensorFlow",
    "cert8.title": "Kubernetes Administrator",
    "cert8.institution": "Cloud Native Computing Foundation",
    "cert8.date": "2023",
    "cert8.description": "Certification en administration Kubernetes",
    "cert9.title": "Apache Spark & Big Data",
    "cert9.institution": "Databricks",
    "cert9.date": "2023",
    "cert9.description": "Certification en traitement de données massives",
    "cert10.title": "Docker Certified Associate",
    "cert10.institution": "Docker",
    "cert10.date": "2023",
    "cert10.description": "Certification en conteneurisation Docker",
    "cert11.title": "MongoDB Developer",
    "cert11.institution": "MongoDB University",
    "cert11.date": "2023",
    "cert11.description": "Certification développeur MongoDB",
    "cert12.title": "React Advanced Patterns",
    "cert12.institution": "Meta",
    "cert12.date": "2023",
    "cert12.description": "Certification avancée en développement React",
    "cert13.title": "DevOps Engineering",
    "cert13.institution": "Microsoft",
    "cert13.date": "2022",
    "cert13.description": "Certification en pratiques DevOps",
    "cert14.title": "Scrum Master Certified",
    "cert14.institution": "Scrum Alliance",
    "cert14.date": "2022",
    "cert14.description": "Certification Scrum Master",
    "cert15.title": "SQL Advanced",
    "cert15.institution": "Oracle",
    "cert15.date": "2022",
    "cert15.description": "Certification avancée en SQL et bases de données",
    "cert16.title": "Cybersecurity Fundamentals",
    "cert16.institution": "CompTIA",
    "cert16.date": "2022",
    "cert16.description": "Certification en fondamentaux de la cybersécurité",
    
    // Education
    "education.master": "Master - Ingénierie des Données et Intelligence Artificielle",
    "education.master.status": "En cours",
    "education.master.description": "Formation avancée en data engineering, machine learning et intelligence artificielle",
    "education.bachelor": "Licence en Informatique - Option Génie Logiciel",
    "education.bachelor.status": "Obtenue",
    "education.bachelor.description": "Formation en développement logiciel, architecture et méthodologies agiles",
    
    // Experience
    "experience.ai-intern.title": "Stagiaire Développeur en Intelligence Artificielle",
    "experience.ai-intern.company": "Orange Digital Center (Sonatel)",
    "experience.ai-intern.location": "Dakar, Sénégal",
    "experience.ai-intern.period": "Juillet 2025 - Octobre 2025",
    "experience.ai-intern.desc1": "Conception et développement de chatbots intelligents pour automatiser la communication et améliorer l'expérience utilisateur",
    "experience.ai-intern.desc2": "Utilisation des services AWS pour le déploiement et l'hébergement d'applications d'intelligence artificielle",
    "experience.ai-intern.desc3": "Contribution à la mise en œuvre de solutions IA innovantes dans le cadre de la transformation numérique du groupe Sonatel",
    "experience.ai-intern.desc4": "Collaboration avec une équipe pluridisciplinaire dans un environnement agile",
    "experience.backend.title": "Développeur Back-End",
    "experience.backend.company": "DSI - Université IBA Der Thiam, Thies",
    "experience.backend.location": "Thiès, Sénégal",
    "experience.backend.period": "Décembre 2023 - Avril 2024",
    "experience.backend.desc1": "Conception d'une application pour gérer les heures complémentaires des professeurs titulaires et des vacataires",
    "experience.backend.desc2": "Utilisation de Laravel côté back-end et React côté front-end",
    "experience.backend.desc3": "Gestion du versioning avec Git/GitLab",
    "experience.web.title": "Web Developer",
    "experience.web.company": "IBS - Parcelles Assainies, Dakar (Remote)",
    "experience.web.location": "Dakar, Sénégal",
    "experience.web.period": "Mai 2024 - Août 2024",
    "experience.web.desc1": "Création et maintenance de sites web développés sous WordPress",
    
    // Skills Categories
    "skills.ai.title": "Intelligence Artificielle & ML",
    "skills.data.title": "Data Engineering",
    "skills.programming.title": "Langages de Programmation",
    "skills.web.title": "Développement Web",
    "skills.cloud.title": "Cloud & DevOps",
    "skills.datascience.title": "Data Science",
    
    // Contact
    "contact.title": "Me Contacter",
    "contact.subtitle": "N'hésitez pas à me contacter pour toute opportunité ou question",
    "contact.name": "Nom complet",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Envoyer le message",
    "contact.success": "Message envoyé avec succès!",
    "contact.info": "Informations de Contact",
    
    // Footer
    "footer.rights": "Tous droits réservés.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.education": "Education",
    "nav.skills": "Skills",
    "nav.experience": "Experience",
    "nav.projects": "Projects",
    "nav.certifications": "Certifications",
    "nav.contact": "Contact",
    
    // Hero
    "hero.greeting": "Hello, I'm",
    "hero.title": "Data & AI Engineer",
    "hero.description": "Master's student in Data Engineering and Artificial Intelligence, passionate about developing innovative AI-based solutions and data analysis.",
    "hero.cta": "Contact Me",
    "hero.projects": "View My Projects",
    "hero.downloadCV": "Download CV",
    
    // About
    "about.title": "About Me",
    "about.intro": "Passionate about artificial intelligence and data engineering",
    "about.p1": "I am currently a Master's student in Data Engineering and Artificial Intelligence, with a solid background in software engineering obtained during my bachelor's degree.",
    "about.p2": "My journey has allowed me to develop deep technical expertise in Machine Learning, Deep Learning, and modern web application development. I am particularly interested in solutions that combine AI and Big Data to solve real-world problems.",
    "about.p3": "Always looking for new challenges, I strive to stay up to date with the latest technologies and methodologies in the field.",
    "about.highlight1.title": "Artificial Intelligence",
    "about.highlight1.description": "Specialization in Machine Learning and Deep Learning",
    "about.highlight2.title": "Data Engineering",
    "about.highlight2.description": "Expertise in Big Data and data pipelines",
    "about.highlight3.title": "Software Engineering",
    "about.highlight3.description": "Strong background in software development",
    
    // Education
    "education.title": "Academic Background",
    
    // Skills
    "skills.title": "Technical Skills",
    "skills.ai": "Artificial Intelligence",
    "skills.data": "Data Engineering",
    "skills.web": "Web Development",
    "skills.database": "Databases",
    "skills.tools": "Tools & DevOps",
    "skills.soft": "Soft Skills",
    
    // Experience
    "experience.title": "Professional Experience",
    
    // Projects
    "projects.title": "Projects",
    "projects.subtitle": "Discover my achievements in Artificial Intelligence and development",
    "projects.filterAll": "All",
    "projects.filterAI": "Artificial Intelligence",
    "projects.filterWeb": "Web Development",
    "projects.filterData": "Data Science",
    "projects.details": "Details",
    "projects.github": "GitHub",
    "projects.demo": "Demo",
    "project1.title": "Intelligent Recommendation System",
    "project1.description": "Development of a Machine Learning-based recommendation system to enhance user experience",
    "project1.detailedDescription": "This project implements a recommendation system using collaborative filtering and deep learning algorithms. It analyzes user behavior to suggest personalized content with 87% accuracy.",
    "project2.title": "Big Data ETL Pipeline",
    "project2.description": "Design of a massive data processing pipeline for real-time analysis",
    "project2.detailedDescription": "Distributed pipeline capable of processing millions of events per second. Uses Apache Spark for parallel processing and Hadoop for distributed storage. Includes real-time monitoring and alerting mechanisms.",
    "project3.title": "Conversational AI Chatbot",
    "project3.description": "Creation of a virtual assistant using natural language processing",
    "project3.detailedDescription": "Intelligent conversational assistant based on transformers, capable of understanding conversation context. Supports multiple languages and easily integrates via REST API.",
    "project4.title": "Data Warehouse Analytics",
    "project4.description": "Implementation of a data warehouse for business intelligence analysis",
    "project4.detailedDescription": "Complete data warehouse architecture with star schema modeling, automated ETL processes, and interactive dashboards. Optimized for complex analytical queries.",
    "project5.title": "Full-Stack Web Application",
    "project5.description": "Development of a complete web platform with authentication and data management",
    "project5.detailedDescription": "Modern MERN stack application with JWT authentication, Redux state management, and responsive user interface. Includes comprehensive unit and integration tests.",
    "project6.title": "Fraud Detection System",
    "project6.description": "ML model for automatic detection of fraudulent transactions",
    "project6.detailedDescription": "Real-time detection system using anomaly detection algorithms. Achieves 95% accuracy with a false positive rate below 2%.",
    "project7.title": "Sentiment Analysis Platform",
    "project7.description": "Automatic sentiment analysis in customer reviews on social media",
    "project7.detailedDescription": "Multi-language sentiment analysis platform using fine-tuned BERT models. Processes thousands of posts per minute with classification into 5 emotional categories.",
    "project8.title": "AI-powered E-commerce",
    "project8.description": "E-commerce site integrating AI-powered personalized recommendations",
    "project8.detailedDescription": "Complete e-commerce platform with hybrid recommendation system, smart cart, and churn prediction. 40% increase in conversion rate.",
    "project9.title": "Computer Vision - Object Recognition",
    "project9.description": "Real-time object detection and classification application",
    "project9.detailedDescription": "Computer vision application using YOLO and custom CNNs. Capable of detecting 80+ object classes in real-time at 30+ FPS.",
    "project10.title": "Real-Time Analytics Dashboard",
    "project10.description": "Interactive dashboard for streaming data visualization",
    "project10.detailedDescription": "Real-time dashboard built with React and D3.js, connected to Kafka for streaming. Includes interactive charts, automatic alerts, and customizable exports.",
    "project11.title": "Automatic Summarization System",
    "project11.description": "Tool for automatic extraction and summarization of large documents",
    "project11.detailedDescription": "Extractive and abstractive summarization tool using BERT and GPT. Capable of summarizing 100+ page documents in seconds while preserving key information.",
    "project12.title": "MLaaS Prediction API",
    "project12.description": "Cloud service to deploy and consume ML models via REST API",
    "project12.detailedDescription": "MLaaS platform enabling rapid ML model deployment. Auto-scaling, integrated monitoring, and automatic API documentation. Deployed on AWS with FastAPI.",
    
    // Certifications
    "certifications.title": "Certifications",
    "certifications.subtitle": "Discover my certificates and distinctions in artificial intelligence and web development.",
    "cert1.title": "Artificial Intelligence Certification",
    "cert1.institution": "FORCE-N",
    "cert1.date": "March 2025",
    "cert1.description": "Certificate of completion for the FORCE-N program recognized by the African Union and Mastercard Foundation",
    "cert2.title": "Web Development Certification",
    "cert2.institution": "Your Institution",
    "cert2.date": "2024",
    "cert2.description": "Full-stack web development certification",
    "cert3.title": "Machine Learning Certification",
    "cert3.institution": "Your Institution",
    "cert3.date": "2024",
    "cert3.description": "Advanced certification in machine learning and deep learning",
    "cert4.title": "AWS Certified Solutions Architect",
    "cert4.institution": "Amazon Web Services",
    "cert4.date": "2024",
    "cert4.description": "AWS cloud architecture certification",
    "cert5.title": "Data Engineering Professional",
    "cert5.institution": "Google Cloud",
    "cert5.date": "2024",
    "cert5.description": "Data engineering certification on GCP",
    "cert6.title": "Python for Data Science",
    "cert6.institution": "IBM",
    "cert6.date": "2023",
    "cert6.description": "Python programming certification for data science",
    "cert7.title": "TensorFlow Developer Certificate",
    "cert7.institution": "Google",
    "cert7.date": "2023",
    "cert7.description": "Official TensorFlow certification",
    "cert8.title": "Kubernetes Administrator",
    "cert8.institution": "Cloud Native Computing Foundation",
    "cert8.date": "2023",
    "cert8.description": "Kubernetes administration certification",
    "cert9.title": "Apache Spark & Big Data",
    "cert9.institution": "Databricks",
    "cert9.date": "2023",
    "cert9.description": "Big data processing certification",
    "cert10.title": "Docker Certified Associate",
    "cert10.institution": "Docker",
    "cert10.date": "2023",
    "cert10.description": "Docker containerization certification",
    "cert11.title": "MongoDB Developer",
    "cert11.institution": "MongoDB University",
    "cert11.date": "2023",
    "cert11.description": "MongoDB developer certification",
    "cert12.title": "React Advanced Patterns",
    "cert12.institution": "Meta",
    "cert12.date": "2023",
    "cert12.description": "Advanced React development certification",
    "cert13.title": "DevOps Engineering",
    "cert13.institution": "Microsoft",
    "cert13.date": "2022",
    "cert13.description": "DevOps practices certification",
    "cert14.title": "Scrum Master Certified",
    "cert14.institution": "Scrum Alliance",
    "cert14.date": "2022",
    "cert14.description": "Scrum Master certification",
    "cert15.title": "SQL Advanced",
    "cert15.institution": "Oracle",
    "cert15.date": "2022",
    "cert15.description": "Advanced SQL and database certification",
    "cert16.title": "Cybersecurity Fundamentals",
    "cert16.institution": "CompTIA",
    "cert16.date": "2022",
    "cert16.description": "Cybersecurity fundamentals certification",
    
    // Education
    "education.master": "Master - Data Engineering and Artificial Intelligence",
    "education.master.status": "In Progress",
    "education.master.description": "Advanced training in data engineering, machine learning and artificial intelligence",
    "education.bachelor": "Bachelor's Degree in Computer Science - Software Engineering",
    "education.bachelor.status": "Obtained",
    "education.bachelor.description": "Training in software development, architecture and agile methodologies",
    
    // Experience
    "experience.ai-intern.title": "AI Developer Intern",
    "experience.ai-intern.company": "Orange Digital Center (Sonatel)",
    "experience.ai-intern.location": "Dakar, Senegal",
    "experience.ai-intern.period": "July 2025 - October 2025",
    "experience.ai-intern.desc1": "Design and development of intelligent chatbots to automate communication and improve user experience",
    "experience.ai-intern.desc2": "Use of AWS services for deployment and hosting of artificial intelligence applications",
    "experience.ai-intern.desc3": "Contribution to the implementation of innovative AI solutions as part of Sonatel Group's digital transformation",
    "experience.ai-intern.desc4": "Collaboration with a multidisciplinary team in an agile environment",
    "experience.backend.title": "Back-End Developer",
    "experience.backend.company": "DSI - IBA Der Thiam University, Thies",
    "experience.backend.location": "Thiès, Senegal",
    "experience.backend.period": "December 2023 - April 2024",
    "experience.backend.desc1": "Design of an application to manage additional hours for full-time and part-time professors",
    "experience.backend.desc2": "Use of Laravel on the back-end and React on the front-end",
    "experience.backend.desc3": "Version management with Git/GitLab",
    "experience.web.title": "Web Developer",
    "experience.web.company": "IBS - Parcelles Assainies, Dakar (Remote)",
    "experience.web.location": "Dakar, Senegal",
    "experience.web.period": "May 2024 - August 2024",
    "experience.web.desc1": "Creation and maintenance of websites developed with WordPress",
    
    // Skills Categories
    "skills.ai.title": "Artificial Intelligence & ML",
    "skills.data.title": "Data Engineering",
    "skills.programming.title": "Programming Languages",
    "skills.web.title": "Web Development",
    "skills.cloud.title": "Cloud & DevOps",
    "skills.datascience.title": "Data Science",
    
    // Contact
    "contact.title": "Contact Me",
    "contact.subtitle": "Feel free to contact me for any opportunity or question",
    "contact.name": "Full Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.success": "Message sent successfully!",
    "contact.info": "Contact Information",
    
    // Footer
    "footer.rights": "All rights reserved.",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
